on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  archs:
    # The host should always be linux
    runs-on: ubuntu-18.04
    name: Build on s390x
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.7
        name: Build artifact
        id: build
        with:
          arch: s390x
          distro: fedora_latest

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-fedora_latest_s390x

          # The shell to run commands with in the container
          shell: /bin/sh

          # Produce a binary artifact and place it in the mounted volume
          run: |
            dnf -y update
            dnf -y install git gcc valgrind cmake
            uname -a;id;uname -m;lscpu | grep Endian
            mkdir build && cd build
            cmake .. && make -j && make check
            rm -rf *
            cmake .. -DSANITIZER=thread
            make -j
            make check

